site_name: Data Science & ML Engineering Portfolio
theme:
  name: material
  palette:
    primary: black
    accent: deep orange

nav:
  - Executive Summary: index.md
  - Core Architectures:
    - Multimodal IDP (LLM ETL): projekty/ocr-pipeline.md
    - InsurTech Pricing Engine: projekty/ubezpieczenia.md
    - AI Half-Marathon Inference: projekty/biegacz-cloud.md